[build]
  publish = "dist"
  command = "npm install && vite build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"
  VITE_API_URL = "/.netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200